sonar.projectKey=raygolib
sonar.projectName=raygolib
sonar.projectVersion=0.1

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/examples/**,**/internal/raylib/**,**/internal/testutils/**,**/dev/**

sonar.go.coverage.reportPaths=dev/coverage/coverage.out
