sonar.projectKey=raygolib
sonar.projectName=raygolib
sonar.projectVersion=0.1

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/examples/**,**/internal/raylib/**,**/cmd/**,**/internal/testutils/**

sonar.go.coverage.reportPaths=coverage/coverage.out
