// Code generated by raygolib/assetgen. DO NOT EDIT.

package assets


// sounds from audio/
type SoundName string

const (
	Click SoundName = "click.ogg"
)

// textures from textures/
type TextureName string

const (
	Enemy TextureName = "enemy.png"
	Player TextureName = "player.png"
)

