// Code generated by raygolib/assetgen. DO NOT EDIT.

package main

// models
type ModelName string

const (
	_2barrel ModelName = "./assets/2barrel.glb"
	Bomb ModelName = "./assets/bomb.glb"
	Cube ModelName = "./assets/cubE.glb"
	Cylinder ModelName = "./assets/cylinder.glb"
	Ghost ModelName = "./assets/ghost.glb"
	Plane ModelName = "./assets/plane.glb"
	Player ModelName = "./assets/player.glb"
	Room ModelName = "./assets/room.glb"
	Screw ModelName = "./assets/screw.glb"
)
